### ISSUE TITLE
설치방법을 알고 싶습니다

### ISSUE THREAD

**Issue by kosehwan** [huny0522/bh-board#1]
안녕하세요 개발자님 

해당 소스를 한번 설치해보고 싶은데요 

http://www.bhboard.com

해당 사이트 접속도 안돼고 사이트에 나와 있는대로  

install을 하려고 해도 동작이 안돼는데요

혹시 설치할 수 있는 방법이 있을까요?

**Comment by huny0522** [comment]
깃헙을 주시하지 못해서 이제 보았습니다.

/index.php 파일에서 배열 변수 $_DEVELOPER_IP에 접속 IP를 등록하시고, 
/Custom/db.info.php 에 DB 정보를 등록하여 주세요.
설정을 완료하셨으면 새로고침을 눌러주세요.
